#!/bin/sh
lock() {
    xscreensaver-command -lock
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        dbus-send --print-reply --system --dest=org.freedesktop.UPower /org/freedektop/UPower.Reboot
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|reboot|shutdown}" 
        exit 2
esac

exit 0
